"""create database metadata cache tables

Revision ID: 490bb217d9d4
Revises: 1b0af03b18c3
Create Date: 2026-08-06 06:11:41.952957

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "490bb217d9d4"
down_revision: str | Sequence[str] | None = "1b0af03b18c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "database_schemas",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("schema_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["database_connections.id"],
            name=op.f("fk_database_schemas_connection_id_database_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_database_schemas_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_database_schemas")),
        sa.UniqueConstraint(
            "connection_id", "schema_name", name="uq_database_schemas_connection_name"
        ),
    )
    op.create_index(
        op.f("ix_database_schemas_connection_id"),
        "database_schemas",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_database_schemas_tenant_id"),
        "database_schemas",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "database_tables",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("schema_id", sa.UUID(), nullable=False),
        sa.Column("table_name", sa.String(length=255), nullable=False),
        sa.Column(
            "table_type", sa.String(length=50), server_default="table", nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("estimated_row_count", sa.BigInteger(), nullable=True),
        sa.Column(
            "primary_key_columns",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_sensitive", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["database_connections.id"],
            name=op.f("fk_database_tables_connection_id_database_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["schema_id"],
            ["database_schemas.id"],
            name=op.f("fk_database_tables_schema_id_database_schemas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_database_tables_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_database_tables")),
        sa.UniqueConstraint(
            "connection_id",
            "schema_id",
            "table_name",
            name="uq_database_tables_connection_schema_name",
        ),
    )
    op.create_index(
        op.f("ix_database_tables_connection_id"),
        "database_tables",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_database_tables_schema_id"),
        "database_tables",
        ["schema_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_database_tables_tenant_id"),
        "database_tables",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "database_columns",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("table_id", sa.UUID(), nullable=False),
        sa.Column("column_name", sa.String(length=255), nullable=False),
        sa.Column("data_type", sa.String(length=100), nullable=False),
        sa.Column("ordinal_position", sa.Integer(), nullable=True),
        sa.Column("is_nullable", sa.Boolean(), nullable=True),
        sa.Column(
            "is_primary_key", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "is_foreign_key", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("is_sensitive", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("referenced_schema", sa.String(length=255), nullable=True),
        sa.Column("referenced_table", sa.String(length=255), nullable=True),
        sa.Column("referenced_column", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "sample_values",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["database_tables.id"],
            name=op.f("fk_database_columns_table_id_database_tables"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_database_columns_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_database_columns")),
        sa.UniqueConstraint(
            "table_id", "column_name", name="uq_database_columns_table_name"
        ),
    )
    op.create_index(
        op.f("ix_database_columns_table_id"),
        "database_columns",
        ["table_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_database_columns_tenant_id"),
        "database_columns",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_database_columns_tenant_id"), table_name="database_columns")
    op.drop_index(op.f("ix_database_columns_table_id"), table_name="database_columns")
    op.drop_table("database_columns")
    op.drop_index(op.f("ix_database_tables_tenant_id"), table_name="database_tables")
    op.drop_index(op.f("ix_database_tables_schema_id"), table_name="database_tables")
    op.drop_index(
        op.f("ix_database_tables_connection_id"), table_name="database_tables"
    )
    op.drop_table("database_tables")
    op.drop_index(op.f("ix_database_schemas_tenant_id"), table_name="database_schemas")
    op.drop_index(
        op.f("ix_database_schemas_connection_id"), table_name="database_schemas"
    )
    op.drop_table("database_schemas")
    # ### end Alembic commands ###
