"""create table and column permissions

Revision ID: af8cc6a401b5
Revises: 490bb217d9d4
Create Date: 2026-08-06 17:07:32.116401

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "af8cc6a401b5"
down_revision: str | Sequence[str] | None = "490bb217d9d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "table_permissions",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("table_id", sa.UUID(), nullable=False),
        sa.Column("can_read", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("can_insert", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("can_update", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("can_delete", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "row_filter",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            (\n                role_id IS NOT NULL\n                AND user_id IS NULL\n            )\n            OR\n            (\n                role_id IS NULL\n                AND user_id IS NOT NULL\n            )\n            ",
            name=op.f("ck_table_permissions_permission_subject"),
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["database_connections.id"],
            name=op.f("fk_table_permissions_connection_id_database_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_table_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["database_tables.id"],
            name=op.f("fk_table_permissions_table_id_database_tables"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_table_permissions_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_table_permissions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_table_permissions")),
        sa.UniqueConstraint(
            "role_id", "table_id", name="uq_table_permissions_role_table"
        ),
        sa.UniqueConstraint(
            "user_id", "table_id", name="uq_table_permissions_user_table"
        ),
    )
    op.create_index(
        op.f("ix_table_permissions_connection_id"),
        "table_permissions",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_table_permissions_role_id"),
        "table_permissions",
        ["role_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_table_permissions_table_id"),
        "table_permissions",
        ["table_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_table_permissions_tenant_id"),
        "table_permissions",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_table_permissions_user_id"),
        "table_permissions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "column_permissions",
        sa.Column("table_permission_id", sa.UUID(), nullable=False),
        sa.Column("column_id", sa.UUID(), nullable=False),
        sa.Column("can_read", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("can_filter", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("can_aggregate", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("mask_type", sa.String(length=50), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["column_id"],
            ["database_columns.id"],
            name=op.f("fk_column_permissions_column_id_database_columns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["table_permission_id"],
            ["table_permissions.id"],
            name=op.f("fk_column_permissions_table_permission_id_table_permissions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_column_permissions")),
        sa.UniqueConstraint(
            "table_permission_id",
            "column_id",
            name="uq_column_permissions_table_permission_column",
        ),
    )
    op.create_index(
        op.f("ix_column_permissions_column_id"),
        "column_permissions",
        ["column_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_column_permissions_table_permission_id"),
        "column_permissions",
        ["table_permission_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_column_permissions_table_permission_id"),
        table_name="column_permissions",
    )
    op.drop_index(
        op.f("ix_column_permissions_column_id"), table_name="column_permissions"
    )
    op.drop_table("column_permissions")
    op.drop_index(op.f("ix_table_permissions_user_id"), table_name="table_permissions")
    op.drop_index(
        op.f("ix_table_permissions_tenant_id"), table_name="table_permissions"
    )
    op.drop_index(op.f("ix_table_permissions_table_id"), table_name="table_permissions")
    op.drop_index(op.f("ix_table_permissions_role_id"), table_name="table_permissions")
    op.drop_index(
        op.f("ix_table_permissions_connection_id"), table_name="table_permissions"
    )
    op.drop_table("table_permissions")
    # ### end Alembic commands ###
